---
driver:
  name: azurerm
  subscription_id: 1e0b427a-d58b-494e-ae4f-ee558463ebbf
  location: 'West Europe'
  machine_size: 'Standard_D1'

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  ssh_key: ~/.ssh/id_kitchen-azurerm

platforms:
  - name: ubuntu-16.04
    driver:
      image_urn: Canonical:UbuntuServer:16.04-LTS:latest

suites:
  - name: default
    run_list:
      - recipe[belfast::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
